import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from "@/src/context/AuthProvider";
import "./globals.css";
import { Toaster } from "@/src/components/ui/sonner";
import { Navbar } from '@/src/components/pageComponents/Navbar';
import Footer from "../components/pageComponents/Footer";

export const metadata: Metadata = {
  title: "backKA",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <AuthProvider>
        <body className={`${poppins.className} flex flex-col min-h-screen m-0 p-0 overflow-x-hidden`}>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </body>
      </AuthProvider>
      
    </html>
  );
}
