import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from "@/src/context/AuthProvider";
import "./globals.css";
import { Toaster } from "@/src/components/ui/sonner";

export const metadata: Metadata = {
  title: "backKA",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={`${poppins.className}`}>
        {children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
