import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from "@/src/context/AuthProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={`${poppins.className}`}>
        {children}
      </body>
      </AuthProvider>
    </html>
  );
}
